// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2wC9lE4iah7ekFPGVDr8SX00-KquTRUo',
    appId: '1:603997412584:web:05341e3ccb1a267b40bd5d',
    messagingSenderId: '603997412584',
    projectId: 'nexus-crm-hr',
    authDomain: 'nexus-crm-hr.firebaseapp.com',
    storageBucket: 'nexus-crm-hr.firebasestorage.app',
    measurementId: 'G-9FFBSLN569',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuXdC97nU65FkK7ikRujKD2cnhacnBSZg',
    appId: '1:603997412584:ios:70e4cf4a7925c9ac40bd5d',
    messagingSenderId: '603997412584',
    projectId: 'nexus-crm-hr',
    storageBucket: 'nexus-crm-hr.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuXdC97nU65FkK7ikRujKD2cnhacnBSZg',
    appId: '1:603997412584:ios:70e4cf4a7925c9ac40bd5d',
    messagingSenderId: '603997412584',
    projectId: 'nexus-crm-hr',
    storageBucket: 'nexus-crm-hr.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAykoSH51qI98ybCUf-qbMt9NAv-Zy788M',
    appId: '1:603997412584:android:662242457e0e5b9a40bd5d',
    messagingSenderId: '603997412584',
    projectId: 'nexus-crm-hr',
    storageBucket: 'nexus-crm-hr.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2wC9lE4iah7ekFPGVDr8SX00-KquTRUo',
    appId: '1:603997412584:web:b153f4a4595342b240bd5d',
    messagingSenderId: '603997412584',
    projectId: 'nexus-crm-hr',
    authDomain: 'nexus-crm-hr.firebaseapp.com',
    storageBucket: 'nexus-crm-hr.firebasestorage.app',
    measurementId: 'G-NXT9CH3N5L',
  );

}